# Generated by Django 4.2.16 on 2026-02-05 21:58

from django.db import migrations
from django.utils.text import slugify


def create_default_data(apps, schema_editor):
    BlogTag = apps.get_model('blog', 'BlogTag')
    BlogCategory = apps.get_model('blog', 'BlogCategory')
    
    # Create default tags - comprehensive list based on profile
    default_tags = [
        # Programming Languages
        'Python', 'C#', 'JavaScript', 'Java', 'C++', 'PHP', 'MATLAB',
        
        # Web Frameworks & Technologies
        'Django', 'React', 'Laravel', 'Node.js', 'NativeScript', 'HTML', 'CSS', 'jQuery',
        
        # Databases
        'MySQL', 'PostgreSQL', 'MongoDB', 'SQLite',
        
        # DevOps & Cloud
        'Microsoft Azure', 'Docker', 'Cloud Computing', 'Virtualization', 'Proxmox',
        
        # AI & Machine Learning
        'Machine Learning', 'AI', 'Deep Learning', 'Neural Networks', 'Data Analysis', 'Big Data',
        
        # IoT & Embedded
        'IoT', 'Industrial IoT', 'Sensor Networks', 'Time-Series Data',
        
        # Software Engineering
        'Software Engineering', 'Agile', 'GitHub', 'DevOps', 'CI/CD', 'JIRA', 'BitBucket',
        
        # Operating Systems & Tools
        'Linux', 'Windows', 'OSX', 'vim', 'VS Code',
        
        # Networking & Protocols
        'Distributed Systems', 'Networking', 'VPN', 'SSH', 'VNC', 'TCP/IP', 'Web Protocols',
        
        # Stream Processing & Messaging
        'Stream Processing', 'Faust', 'Message Queuing', 'VerneMQ',
        
        # Monitoring
        'Prometheus', 'Grafana', 'Monitoring',
        
        # Physics & Science
        'Physics', 'Computational Physics', 'Mathematical Modeling', 'Simulation',
        'Monte Carlo', 'Numerical Methods', 'LaTeX', 'Medical Imaging',
        
        # Development Practices
        'Tutorial', 'How-to', 'Best Practices', 'Performance', 'Security', 
        'Testing', 'Unit Testing', 'Code Quality', 'Refactoring',
        
        # Architecture
        'API', 'Backend', 'Frontend', 'Full Stack', 'Microservices',
        
        # Data Engineering
        'Data Pipeline', 'Data Compression',
        
        # Web Stack
        'LAMP Stack', 'Single Page Application',
    ]
    
    for tag_name in default_tags:
        slug = slugify(tag_name)
        if not BlogTag.objects.filter(slug=slug).exists():
            BlogTag.objects.create(name=tag_name, slug=slug)
    
    # Create default categories - expanded with AI and more specific areas
    default_categories = [
        ('Software Development', 'Articles about programming, software engineering, and development practices'),
        ('Web Development', 'Frontend, backend, and full-stack web development topics'),
        ('Artificial Intelligence & ML', 'Deep dive into AI, machine learning algorithms, neural networks, and AI applications'),
        ('Data Science & Analytics', 'Data analysis, big data processing, and statistical methods'),
        ('Cloud & DevOps', 'Cloud computing, containerization, CI/CD, and infrastructure'),
        ('Database & Storage', 'Database design, optimization, query performance, and data management'),
        ('IoT & Embedded Systems', 'Internet of Things, industrial IoT, embedded systems, and sensor technologies'),
        ('Physics & Mathematics', 'Computational physics, mathematical modeling, simulations, and scientific computing'),
        ('System Architecture', 'Distributed systems, microservices, scalability, and architectural patterns'),
        ('Stream Processing & Real-Time', 'Real-time data processing, stream analytics, and time-series analysis'),
        ('Monitoring & Performance', 'Application monitoring, performance optimization, and observability'),
        ('Networking & Security', 'Network protocols, security best practices, and infrastructure security'),
        ('Tutorials & How-To', 'Step-by-step guides, practical tutorials, and learning resources'),
        ('Career & Professional Development', 'Professional growth, learning strategies, and career insights'),
        ('Best Practices & Code Quality', 'Code quality, maintainability, testing, and software engineering standards'),
    ]
    
    for name, description in default_categories:
        slug = slugify(name)
        if not BlogCategory.objects.filter(slug=slug).exists():
            BlogCategory.objects.create(name=name, slug=slug, description=description)


def remove_default_data(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_data, remove_default_data),
    ]
