# Generated by Django 4.2.16 on 2026-02-06 02:48

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_add_default_tags_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default=blog.models.get_default_author, max_length=100),
        ),
    ]
