# Generated by Django 4.2.16 on 2026-02-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='featured_image_caption',
            field=models.CharField(blank=True, help_text='Caption for the featured image', max_length=300),
        ),
    ]
