# Generated by Django 4.2.16 on 2026-02-06 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='show_projects_link',
            field=models.BooleanField(default=True, help_text='Show the Projects link in the navigation bar'),
        ),
    ]
