# Generated by Django 4.2.16 on 2026-02-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_add_show_projects_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='copyright_text',
            field=models.CharField(default='Your Name. All rights reserved.', help_text='Copyright text displayed in footer (year is added automatically)', max_length=200),
        ),
    ]
