# Generated by Django 4.2.28 on 2026-02-08 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_siteconfiguration_copyright_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='x_url',
            field=models.URLField(blank=True, default='https://x.com/yourusername', help_text='Full X (Twitter) profile URL'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='x_username',
            field=models.CharField(blank=True, default='yourusername', help_text='X (Twitter) username (without @)', max_length=100),
        ),
    ]
